[theme]
primaryColor="#FF4B4B"  # Vermelho vibrante para botões e destaques
backgroundColor="#FFFFFF"  # Fundo branco para clareza
secondaryBackgroundColor="#F0F2F6"  # Cinza claro para contraste
textColor="#262730"  # Texto escuro para legibilidade
font="sans serif"